# Generated by Django 3.2 on 2021-07-31 12:51

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1994), users.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='Engineering', max_length=40),
        ),
    ]
