# Generated by Django 3.2 on 2021-07-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210731_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year',
            new_name='year_of_joining',
        ),
    ]
