# Generated by Django 3.2 on 2021-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_year_profile_year_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(default='Engineering', max_length=40),
        ),
    ]
